services:
  nextjsblog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjsblog
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules